import jsPDF from 'jspdf';
import { User } from '../context/AuthContext';

interface BaseReportData {
  user: User;
  date: string;
  reportType: string;
}

interface ImageAnalysisReport extends BaseReportData {
  diagnosis: string;
  confidence: number;
  severity: string;
  description: string;
  treatment: string;
  precautions: string[];
}

interface MultiModelReport extends BaseReportData {
  models: Array<{
    modelName: string;
    confidence: number;
    latency: number;
    findings: string[];
  }>;
  consensus: number;
  geminiAnalysis: {
    diagnosis: string;
    severity: string;
    description: string;
    treatment: string;
    precautions: string[];
  };
}

interface ChatConsultationReport extends BaseReportData {
  messages: Array<{
    role: 'user' | 'assistant';
    content: string;
    timestamp: string;
  }>;
  summary: string;
}

// Add header to PDF
function addHeader(pdf: jsPDF, title: string) {
  let yPosition = 20;
  
  // Logo/Title
  pdf.setFontSize(24);
  pdf.setTextColor(20, 184, 166); // teal
  pdf.text('AROGYA', 105, yPosition, { align: 'center' });
  
  yPosition += 8;
  pdf.setFontSize(10);
  pdf.setTextColor(100, 100, 100);
  pdf.text('AI-Powered Health Consultation Platform', 105, yPosition, { align: 'center' });
  
  yPosition += 10;
  pdf.setFontSize(18);
  pdf.setTextColor(0, 0, 0);
  pdf.text(title, 105, yPosition, { align: 'center' });
  
  yPosition += 8;
  pdf.setDrawColor(20, 184, 166);
  pdf.setLineWidth(0.5);
  pdf.line(20, yPosition, 190, yPosition);
  
  return yPosition + 10;
}

// Add patient info section
function addPatientInfo(pdf: jsPDF, user: User, date: string, yPosition: number) {
  pdf.setFontSize(12);
  pdf.setTextColor(20, 184, 166);
  pdf.text('PATIENT INFORMATION', 20, yPosition);
  
  yPosition += 8;
  pdf.setFontSize(10);
  pdf.setTextColor(0, 0, 0);
  
  pdf.text(`Name: ${user.firstName} ${user.lastName}`, 20, yPosition);
  yPosition += 6;
  pdf.text(`Sex: ${user.sex.charAt(0).toUpperCase() + user.sex.slice(1)}`, 20, yPosition);
  yPosition += 6;
  pdf.text(`Age Group: ${user.ageGroup} years`, 20, yPosition);
  yPosition += 6;
  pdf.text(`Email: ${user.email}`, 20, yPosition);
  yPosition += 6;
  pdf.text(`Report Date: ${date}`, 20, yPosition);
  
  yPosition += 10;
  pdf.setDrawColor(200, 200, 200);
  pdf.setLineWidth(0.3);
  pdf.line(20, yPosition, 190, yPosition);
  
  return yPosition + 10;
}

// Add disclaimer footer
function addDisclaimer(pdf: jsPDF, yPosition: number) {
  const pageHeight = pdf.internal.pageSize.getHeight();
  
  if (yPosition > pageHeight - 40) {
    pdf.addPage();
    yPosition = 20;
  }
  
  yPosition += 10;
  pdf.setFontSize(10);
  pdf.setTextColor(220, 38, 38); // red
  pdf.text('⚠️ MEDICAL DISCLAIMER', 20, yPosition);
  
  yPosition += 7;
  pdf.setFontSize(9);
  pdf.setTextColor(80, 80, 80);
  const disclaimerText = 'This report is generated by AI and is for informational purposes only. It is NOT a substitute for professional medical advice, diagnosis, or treatment. Always consult a qualified healthcare provider for medical concerns. For emergencies, call your local emergency services immediately.';
  const wrappedDisclaimer = pdf.splitTextToSize(disclaimerText, 170);
  pdf.text(wrappedDisclaimer, 20, yPosition);
  
  // Footer
  const footerY = pageHeight - 15;
  pdf.setFontSize(8);
  pdf.setTextColor(150, 150, 150);
  pdf.text(`Generated by Arogya Platform | ${new Date().toLocaleString()}`, 105, footerY, { align: 'center' });
}

// Generate Image Analysis Report
export function generateImageAnalysisReport(data: ImageAnalysisReport): void {
  const pdf = new jsPDF();
  let yPosition = addHeader(pdf, 'IMAGE ANALYSIS REPORT');
  yPosition = addPatientInfo(pdf, data.user, data.date, yPosition);
  
  // Analysis Results
  pdf.setFontSize(12);
  pdf.setTextColor(20, 184, 166);
  pdf.text('ANALYSIS RESULTS', 20, yPosition);
  
  yPosition += 8;
  pdf.setFontSize(10);
  pdf.setTextColor(0, 0, 0);
  
  pdf.setFont(undefined, 'bold');
  pdf.text(`Diagnosis: ${data.diagnosis}`, 20, yPosition);
  yPosition += 6;
  
  pdf.setFont(undefined, 'normal');
  pdf.text(`Confidence Level: ${(data.confidence * 100).toFixed(1)}%`, 20, yPosition);
  yPosition += 6;
  pdf.text(`Severity: ${data.severity}`, 20, yPosition);
  
  yPosition += 10;
  pdf.setFont(undefined, 'bold');
  pdf.text('Description:', 20, yPosition);
  yPosition += 6;
  pdf.setFont(undefined, 'normal');
  const wrappedDesc = pdf.splitTextToSize(data.description, 170);
  pdf.text(wrappedDesc, 20, yPosition);
  yPosition += wrappedDesc.length * 5 + 5;
  
  pdf.setFont(undefined, 'bold');
  pdf.text('Treatment Recommendations:', 20, yPosition);
  yPosition += 6;
  pdf.setFont(undefined, 'normal');
  const wrappedTreatment = pdf.splitTextToSize(data.treatment, 170);
  pdf.text(wrappedTreatment, 20, yPosition);
  yPosition += wrappedTreatment.length * 5 + 5;
  
  // Precautions
  if (data.precautions && data.precautions.length > 0) {
    pdf.setFont(undefined, 'bold');
    pdf.text('Precautions:', 20, yPosition);
    yPosition += 6;
    pdf.setFont(undefined, 'normal');
    
    data.precautions.forEach((precaution, index) => {
      const wrappedPrecaution = pdf.splitTextToSize(`${index + 1}. ${precaution}`, 165);
      pdf.text(wrappedPrecaution, 25, yPosition);
      yPosition += wrappedPrecaution.length * 5 + 3;
    });
  }
  
  addDisclaimer(pdf, yPosition);
  pdf.save(`image_analysis_report_${new Date().getTime()}.pdf`);
}

// Generate Multi-Model Comparison Report
export function generateMultiModelReport(data: MultiModelReport): void {
  const pdf = new jsPDF();
  let yPosition = addHeader(pdf, 'MULTI-MODEL COMPARISON REPORT');
  yPosition = addPatientInfo(pdf, data.user, data.date, yPosition);
  
  // Consensus
  pdf.setFontSize(12);
  pdf.setTextColor(20, 184, 166);
  pdf.text('CONSENSUS ANALYSIS', 20, yPosition);
  
  yPosition += 8;
  pdf.setFontSize(11);
  pdf.setTextColor(0, 0, 0);
  pdf.setFont(undefined, 'bold');
  pdf.text(`Average Confidence: ${data.consensus.toFixed(1)}%`, 20, yPosition);
  yPosition += 6;
  pdf.setFont(undefined, 'normal');
  pdf.text(`Models Analyzed: ${data.models.length}`, 20, yPosition);
  
  yPosition += 10;
  pdf.setDrawColor(200, 200, 200);
  pdf.line(20, yPosition, 190, yPosition);
  yPosition += 8;
  
  // Performance Summary (Bar Chart Data)
  pdf.setFontSize(12);
  pdf.setTextColor(20, 184, 166);
  pdf.text('PERFORMANCE COMPARISON SUMMARY', 20, yPosition);
  yPosition += 8;
  
  // Find best performers
  const fastestModel = data.models.reduce((min, m) => m.latency < min.latency ? m : min);
  const mostAccurate = data.models.reduce((max, m) => m.confidence > max.confidence ? m : max);
  const avgLatency = data.models.reduce((sum, m) => sum + m.latency, 0) / data.models.length;
  const avgAccuracy = data.models.reduce((sum, m) => sum + m.confidence, 0) / data.models.length;
  
  pdf.setFontSize(10);
  pdf.setTextColor(0, 0, 0);
  
  // Performance metrics in a box
  pdf.setDrawColor(20, 184, 166);
  pdf.setLineWidth(0.5);
  pdf.rect(20, yPosition, 170, 35);
  
  yPosition += 7;
  pdf.setFont(undefined, 'bold');
  pdf.text(`Fastest Model: ${fastestModel.modelName}`, 25, yPosition);
  pdf.setFont(undefined, 'normal');
  pdf.text(`(${fastestModel.latency.toFixed(2)}s)`, 90, yPosition);
  
  yPosition += 7;
  pdf.setFont(undefined, 'bold');
  pdf.text(`Most Accurate: ${mostAccurate.modelName}`, 25, yPosition);
  pdf.setFont(undefined, 'normal');
  pdf.text(`(${mostAccurate.confidence.toFixed(1)}%)`, 90, yPosition);
  
  yPosition += 7;
  pdf.setFont(undefined, 'bold');
  pdf.text(`Average Response Time:`, 25, yPosition);
  pdf.setFont(undefined, 'normal');
  pdf.text(`${avgLatency.toFixed(2)} seconds`, 90, yPosition);
  
  yPosition += 7;
  pdf.setFont(undefined, 'bold');
  pdf.text(`Average Accuracy:`, 25, yPosition);
  pdf.setFont(undefined, 'normal');
  pdf.text(`${avgAccuracy.toFixed(1)}%`, 90, yPosition);
  
  yPosition += 15;
  pdf.setDrawColor(200, 200, 200);
  pdf.line(20, yPosition, 190, yPosition);
  yPosition += 8;
  
  // Model Results
  pdf.setFontSize(12);
  pdf.setTextColor(20, 184, 166);
  pdf.text('INDIVIDUAL MODEL RESULTS', 20, yPosition);
  yPosition += 8;
  
  data.models.forEach((model, index) => {
    if (yPosition > 250) {
      pdf.addPage();
      yPosition = 20;
    }
    
    pdf.setFontSize(11);
    pdf.setTextColor(0, 0, 0);
    pdf.setFont(undefined, 'bold');
    pdf.text(`${index + 1}. ${model.modelName}`, 20, yPosition);
    yPosition += 6;
    
    pdf.setFontSize(10);
    pdf.setFont(undefined, 'normal');
    pdf.text(`Confidence: ${model.confidence.toFixed(1)}%`, 25, yPosition);
    yPosition += 5;
    pdf.text(`Response Time: ${model.latency.toFixed(2)}s (${(model.latency * 1000).toFixed(0)}ms)`, 25, yPosition);
    yPosition += 5;
    
    if (model.findings && model.findings.length > 0) {
      pdf.text('Key Findings:', 25, yPosition);
      yPosition += 5;
      model.findings.forEach((finding) => {
        if (yPosition > 270) {
          pdf.addPage();
          yPosition = 20;
        }
        const wrapped = pdf.splitTextToSize(`• ${finding}`, 160);
        pdf.text(wrapped, 30, yPosition);
        yPosition += wrapped.length * 5;
      });
    }
    
    yPosition += 5;
  });
  
  // Gemini Detailed Analysis
  if (yPosition > 230) {
    pdf.addPage();
    yPosition = 20;
  }
  
  yPosition += 5;
  pdf.setFontSize(12);
  pdf.setTextColor(20, 184, 166);
  pdf.text('DETAILED ANALYSIS (Gemini AI)', 20, yPosition);
  yPosition += 8;
  
  pdf.setFontSize(10);
  pdf.setTextColor(0, 0, 0);
  pdf.setFont(undefined, 'bold');
  pdf.text(`Diagnosis: ${data.geminiAnalysis.diagnosis}`, 20, yPosition);
  yPosition += 6;
  pdf.setFont(undefined, 'normal');
  pdf.text(`Severity: ${data.geminiAnalysis.severity}`, 20, yPosition);
  yPosition += 8;
  
  pdf.setFont(undefined, 'bold');
  pdf.text('Description:', 20, yPosition);
  yPosition += 6;
  pdf.setFont(undefined, 'normal');
  const wrappedDesc = pdf.splitTextToSize(data.geminiAnalysis.description, 170);
  pdf.text(wrappedDesc, 20, yPosition);
  yPosition += wrappedDesc.length * 5 + 5;
  
  if (yPosition > 240) {
    pdf.addPage();
    yPosition = 20;
  }
  
  pdf.setFont(undefined, 'bold');
  pdf.text('Treatment Recommendations:', 20, yPosition);
  yPosition += 6;
  pdf.setFont(undefined, 'normal');
  const wrappedTreatment = pdf.splitTextToSize(data.geminiAnalysis.treatment, 170);
  pdf.text(wrappedTreatment, 20, yPosition);
  yPosition += wrappedTreatment.length * 5 + 5;
  
  // Precautions
  if (data.geminiAnalysis.precautions && data.geminiAnalysis.precautions.length > 0) {
    pdf.setFont(undefined, 'bold');
    pdf.text('Precautions:', 20, yPosition);
    yPosition += 6;
    pdf.setFont(undefined, 'normal');
    
    data.geminiAnalysis.precautions.forEach((precaution, index) => {
      if (yPosition > 270) {
        pdf.addPage();
        yPosition = 20;
      }
      const wrappedPrecaution = pdf.splitTextToSize(`${index + 1}. ${precaution}`, 165);
      pdf.text(wrappedPrecaution, 25, yPosition);
      yPosition += wrappedPrecaution.length * 5 + 3;
    });
  }
  
  addDisclaimer(pdf, yPosition);
  pdf.save(`multi_model_comparison_${new Date().getTime()}.pdf`);
}

// Generate Chat Consultation Report
export function generateChatReport(data: ChatConsultationReport): void {
  const pdf = new jsPDF();
  let yPosition = addHeader(pdf, 'CHAT CONSULTATION REPORT');
  yPosition = addPatientInfo(pdf, data.user, data.date, yPosition);
  
  // Summary
  if (data.summary) {
    pdf.setFontSize(12);
    pdf.setTextColor(20, 184, 166);
    pdf.text('CONSULTATION SUMMARY', 20, yPosition);
    yPosition += 8;
    
    pdf.setFontSize(10);
    pdf.setTextColor(0, 0, 0);
    const wrappedSummary = pdf.splitTextToSize(data.summary, 170);
    pdf.text(wrappedSummary, 20, yPosition);
    yPosition += wrappedSummary.length * 5 + 10;
    
    pdf.setDrawColor(200, 200, 200);
    pdf.line(20, yPosition, 190, yPosition);
    yPosition += 8;
  }
  
  // Conversation
  pdf.setFontSize(12);
  pdf.setTextColor(20, 184, 166);
  pdf.text('CONVERSATION TRANSCRIPT', 20, yPosition);
  yPosition += 8;
  
  data.messages.forEach((message, index) => {
    if (yPosition > 260) {
      pdf.addPage();
      yPosition = 20;
    }
    
    pdf.setFontSize(9);
    pdf.setTextColor(100, 100, 100);
    pdf.text(`${message.timestamp} - ${message.role === 'user' ? 'You' : 'AI Assistant'}`, 20, yPosition);
    yPosition += 5;
    
    pdf.setFontSize(10);
    pdf.setTextColor(0, 0, 0);
    const wrappedMessage = pdf.splitTextToSize(message.content, 170);
    pdf.text(wrappedMessage, 20, yPosition);
    yPosition += wrappedMessage.length * 5 + 8;
  });
  
  addDisclaimer(pdf, yPosition);
  pdf.save(`chat_consultation_${new Date().getTime()}.pdf`);
}

// Generate Voice Consultation Report
export function generateVoiceReport(data: ChatConsultationReport): void {
  const pdf = new jsPDF();
  let yPosition = addHeader(pdf, 'VOICE CONSULTATION REPORT');
  yPosition = addPatientInfo(pdf, data.user, data.date, yPosition);
  
  // Summary
  if (data.summary) {
    pdf.setFontSize(12);
    pdf.setTextColor(20, 184, 166);
    pdf.text('CONSULTATION SUMMARY', 20, yPosition);
    yPosition += 8;
    
    pdf.setFontSize(10);
    pdf.setTextColor(0, 0, 0);
    const wrappedSummary = pdf.splitTextToSize(data.summary, 170);
    pdf.text(wrappedSummary, 20, yPosition);
    yPosition += wrappedSummary.length * 5 + 10;
    
    pdf.setDrawColor(200, 200, 200);
    pdf.line(20, yPosition, 190, yPosition);
    yPosition += 8;
  }
  
  // Transcript
  pdf.setFontSize(12);
  pdf.setTextColor(20, 184, 166);
  pdf.text('VOICE TRANSCRIPT', 20, yPosition);
  yPosition += 8;
  
  data.messages.forEach((message, index) => {
    if (yPosition > 260) {
      pdf.addPage();
      yPosition = 20;
    }
    
    pdf.setFontSize(9);
    pdf.setTextColor(100, 100, 100);
    pdf.text(`${message.timestamp} - ${message.role === 'user' ? 'You' : 'AI Assistant'}`, 20, yPosition);
    yPosition += 5;
    
    pdf.setFontSize(10);
    pdf.setTextColor(0, 0, 0);
    const wrappedMessage = pdf.splitTextToSize(message.content, 170);
    pdf.text(wrappedMessage, 20, yPosition);
    yPosition += wrappedMessage.length * 5 + 8;
  });
  
  addDisclaimer(pdf, yPosition);
  pdf.save(`voice_consultation_${new Date().getTime()}.pdf`);
}
